name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  # for goreleaser
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: (setup) sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      
      - name: (setup) environment variables for sccache
        shell: bash
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> "$GITHUB_ENV"
          echo "RUSTC_WRAPPER=sccache" >> "$GITHUB_ENV"

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-shared-key: setup-rust-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock') }}
          target: "x86_64-unknown-linux-gnu, x86_64-apple-darwin, x86_64-pc-windows-gnu, aarch64-unknown-linux-gnu, aarch64-apple-darwin"
          rustflags: "" # override default rustflags

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true

      - name: Install zig
        uses: mlugg/setup-zig@v2

      - name: Install cargo-zigbuild
        run: |
          cargo install cargo-zigbuild
